ALTER TYPE "BusinessType" ADD VALUE IF NOT EXISTS 'CONTRACTOR';
ALTER TYPE "BusinessType" ADD VALUE IF NOT EXISTS 'REAL_ESTATE_BROKERAGE';
ALTER TYPE "BusinessType" ADD VALUE IF NOT EXISTS 'VACATION_RENTAL';
